services:
  ui-image:
    image: ui-image:latest
    ports:
      - "3001:3000"
    networks:
      - my_network
  identity-image:
    image: identity-image:latest
    ports:
      - "8192:8191"
    networks:
      - my_network
  employee-image:
    image: employee-image:latest
    ports:
      - "8091:8090"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
